let bh="BloodHound";
let bang="Bangalore";
let cau="Caustic";
let gib="Gibraltar";
let oct="Octane";
let path="Pathfinder";
let rev="Revenant";
let valk="Valkurie";
let watt="Wattson";
let wr="Wraith";

var img1="img/bh.jpg";
var img2="img/bang.jpg";
var img3="img/Caustic.jpg";
var img4="img/gibby.jpg";
var img5="img/octane.png";
var img6="img/pathy.png";
var img7="img/rev.png";
var img8="img/valk.jpg";
var img9="img/wattson.jpg";
var img10="img/wraith.png";

document.write(`This is ${bh}`);
document.write(`<img src="${img1}">`);
document.write(`This is ${bang}`);
document.write(`<img src="${img2}">`);
document.write(`This is ${cau}`);
document.write(`<img src="${img3}">`);
document.write(`This is ${gib}`);
document.write(`<img src="${img4}">`);
document.write(`This is ${oct}`);
document.write(`<img src="${img5}">`);
document.write(`This is ${path}`);
document.write(`<img src="${img6}">`);
document.write(`This is ${rev}`);
document.write(`<img src="${img7}">`);
document.write(`This is ${valk}`);
document.write(`<img src="${img8}">`);
document.write(`This is ${watt}`);
document.write(`<img src="${img9}">`);
document.write(`This is ${wr}`);
document.write(`<img src="${img10}">`);